# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.15.5
          check-latest: true
          registry-url: https://npm.pkg.github.com/
          scope: '@thisiswunder'
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN}}
      - name: Install Yarn
        run: npm install -g plugman
      - run: npm i
      - run: npm pack && rm -rf ./dist/*.tgz && mv *.tgz ./dist/release.tgz
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN}}